name: Build Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies your script might need here
        # pip install -r requirements.txt

    - name: Run build script
      run: python build.py

    - name: Commit and push release.json
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add release.json
        git commit -m 'Generate release.json'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}